### PR TITLE
Point fullVersions at the correct generated file

### PR DESCRIPTION
**Pull request by malept**
FYI, this bug is breaking projects created via Electron Forge :smile:

Perhaps there should be some basic smoketests, to prevent this in the future?

### CODE REVIEW

**Comment by Kilian** [comment]
...ouch.

**Comment by malept** [comment]
Please let me know when you've released a new version :smile:

Also, thanks for the quick response! 👍

**Comment by Kilian** [comment]
Thanks <3 I'll see if i can use some of [Browserlist](https://github.com/ai/browserslist)'s  tests for this.

**Comment by Kilian** [comment]
@malept Just pushed 1.2.4 to npm.

**Comment by malept** [comment]
@Kilian much appreciated!

**Pull request merged**
