### PR TITLE
fix: map chromium version to lowest shipped electron version

### PR DESCRIPTION
**Pull request by JLHwung**
This PR maps chromium versions as the lowest electron versions shipped. For example, the following electron version
```
electron 9.0
electron 9.1
electron 9.2
electron 9.3
```
all ship `chromium 83`. Previously we return `electron 9.3` for `chromiumVersions["83"]` since `chromiumVersions[chromeVersion]` is overwritten by higher versions. In this PR we return `electron 9.0` because it is the _lowest_ electron version that ships chromium 83.

**Context**
`@babel/preset-env` uses `chromiumVersions` to generate compat data for electron users. When a JavaScript feature is implemented in Chrome M83, Babel considers `electron 9.3` as the lowest version. With this change Babel can mark `electron 9.0` as supported so we can ship untranspiled JavaScript features for electron 9.0 users.

### CODE REVIEW

**Comment by Kilian** [comment]
I'm not against this change but I'd like to know where this is used now.

As far as I'm aware it uses Electron versions to map to Chrome (like the name of the package), not the other way around: https://github.com/babel/babel/blob/eea156b2cb8deecfcf82d52aa1b71ba4995c7d68/packages/babel-compat-data/scripts/utils-build-data.js#L7

Can you point me to the code where `@babel/preset-env` uses chromiumVersions?

**Comment by JLHwung** [comment]
@Kilian It is used in https://github.com/babel/babel/pull/12073/files#diff-09f99be7c7196957e3752d2a0985fef7 and will get merged soon. Babel used to import `versions` but essentially we are inserting electron support data from chrome support data so I believe Babel should have imported `chromiumVersions`.

**Comment by Kilian** [comment]
awesome, glad to merge this :)

**Comment by Kilian** [comment]
Will be picked up by the next automated update, thanks @JLHwung!

**Pull request merged**
